# Generated by Django 3.2.6 on 2021-09-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('file', models.FileField(upload_to='docs')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
